version: "3.0"

services:
  city-db:
    image: postgres:latest
    container_name: city-db
    environment:
      - POSTGRES_DB=city
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - 5432:5432

  city-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: city-app:dev
    container_name: city-app-dev
    ports:
      - "8008:8008"
    networks:
      default:
        aliases:
          - city-app