spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:cities

  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
city:
  load-on-startup: true
  filename: "cities.csv"

server:
  port: 8008
logging:
  level:
    root: info