spring:
  jpa:
#    database: postgresql
    database: h2
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
#    url: localhost:5432/test
  h2:
    console:
      enabled: true

city:
  load-on-startup: true
  filename: "cities.csv"
server:
  port: 8008