spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password

  liquibase:
    enabled: true
    change-log: /data/changelog/db.changelog.yaml
    url: ${spring.datasource.url}
    database-change-log-table: schema_history
    database-change-log-lock-table: schema_lock_history
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8008
logging:
  level:
    root: info

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger
